### ISSUE TITLE
No volume control

### ISSUE THREAD

**Issue by blackcolt** [marcelkordek/homebridge-harman-kardon-avr#8]
Can't see any vol control, there is a setting I need to change or something?
Also, all the inputs are "On" all the time.

**Comment by marcelkordek** [comment]
Hi, the plugin simulates a television. The volume control only works via the remote app in the lockscreen. When the AVR is selected, the volume of the AVR can be changed using the volume buttons on the iPhone. 
Yes, it is always displayed as "ON" because the current input can unfortunately be read out from the AVR.

**Comment by blackcolt** [comment]
Thanks, will check it :)
